### PR TITLE
getRelativePosition

### PR DESCRIPTION
**Pull request by kurkle**

### CODE REVIEW

**Comment by stockiNail** [comment]
let me rebase my branch

**Comment by kurkle** [comment]
Just to let you see what I'm trying to say. If you have a better solution, let's have that instead :)

**Comment by stockiNail** [comment]
THANKS!!! Apologizes but I couldn't have implemented it like you did! Personally I prefer less generalized calculations but it still seems very clear to me

**Comment by kurkle** [comment]
I personally prefer SIMPLE generalized functions :)

Something went wrong with the rebase or merge.

**Comment by stockiNail** [comment]
> I personally prefer SIMPLE generalized functions :)

I have seen! no problem for my side... Probably I'll always need your help for this

**Comment by stockiNail** [comment]
@kurkle last thing from my side... I promise you no more PR with enhancements till next version, My TODO is almost empty.

**Pull request merged**
